<?php
namespace Plugins\FluxAPI\Permission;


class User extends \FluxAPI\Permission
{
    public function hasControllerAccess($controller_name, $action = NULL)
    {
        if ($controller_name == 'User') {
            if (!empty($action)) {
                switch($action) {
                    case 'login':
                    case 'logout':
                    case 'getCurrent':
                        return TRUE;
                        break;

                    default:
                        return parent::hasControllerAccess($controller_name, $action);
                }
            } else {
                return TRUE;
            }
        } else {
            return parent::hasControllerAccess($controller_name, $action);
        }
    }

    public function hasModelAccess($model_name, \FluxAPI\Model $model = NULL, $action = NULL)
    {
        return parent::hasModelAccess($model_name, $model, $action); // TODO: Change the autogenerated stub
    }
}